name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/lambda/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r backend/lambda/requirements.txt -t backend/lambda/

      - name: Zip Lambda package
        run: |
          cd backend/lambda
          zip -r ../../lambda_package.zip .

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Create or Update Lambda
        run: |
          set +e
          aws lambda get-function --function-name StudentLambda
          if [ $? -ne 0 ]; then
            echo "Lambda does NOT exist. Creating..."
            aws lambda create-function \
              --function-name StudentLambda \
              --runtime python3.10 \
              --role arn:aws:iam::027419661883:role/LambdaSageMakerDynamoRole \
              --handler handler.lambda_handler \
              --zip-file fileb://lambda_package.zip
          else
            echo "Lambda exists. Updating..."
            aws lambda update-function-code \
              --function-name StudentLambda \
              --zip-file fileb://lambda_package.zip
          fi
